### ISSUE TITLE
项目起来后addEventListener报错

### ISSUE THREAD

**Issue by lifangpeng** [wocwin/wocwin-admin#3]
rollPane.vue:21 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')  ScrollPane.vue:21:1
 
发现这行代码有
const scrollWrapper = computed(() => proxy.$refs.scrollContainer.$refs.wrap$);

onMounted(() => {
  scrollWrapper.value.addEventListener('scroll', emitScroll, true)
})

**Comment by wocwin** [comment]
> rollPane.vue:21 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener') ScrollPane.vue:21:1
> 
> 发现这行代码有 const scrollWrapper = computed(() => proxy.$refs.scrollContainer.$refs.wrap$);
> 
> onMounted(() => { scrollWrapper.value.addEventListener('scroll', emitScroll, true) })

我跑起来没有报错！
![image](https://user-images.githubusercontent.com/37534478/231726101-468d445a-957e-4c06-8373-c7c9160d8236.png)

**Comment by lifangpeng** [comment]
> > rollPane.vue:21 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener') ScrollPane.vue:21:1
> > 发现这行代码有 const scrollWrapper = computed(() => proxy.$refs.scrollContainer.$refs.wrap$);
> > onMounted(() => { scrollWrapper.value.addEventListener('scroll', emitScroll, true) })
> 
> 我跑起来没有报错！ ![image](https://user-images.githubusercontent.com/37534478/231726101-468d445a-957e-4c06-8373-c7c9160d8236.png)

![image](https://user-images.githubusercontent.com/20722489/231727834-3c2dad85-3f32-4dc1-ab3e-fcf86af449a5.png)

**Comment by wocwin** [comment]
> > > rollPane.vue:21 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener') ScrollPane.vue:21:1
> > > 发现这行代码有 const scrollWrapper = computed(() => proxy.$refs.scrollContainer.$refs.wrap$);
> > > onMounted(() => { scrollWrapper.value.addEventListener('scroll', emitScroll, true) })
> > 
> > 
> > 我跑起来没有报错！ ![image](https://user-images.githubusercontent.com/37534478/231726101-468d445a-957e-4c06-8373-c7c9160d8236.png)
> 
> ![image](https://user-images.githubusercontent.com/20722489/231727834-3c2dad85-3f32-4dc1-ab3e-fcf86af449a5.png)

看图片，还是你依赖安装不全吧！你删掉重新安装一下

**Comment by lifangpeng** [comment]
这里是不是和那个t-ui-plus有关？

**Comment by wocwin** [comment]
> 这里是不是和那个t-ui-plus有关？

所有页面都是用了这个组件库的UI

**Comment by wocwin** [comment]
> 这里是不是和那个t-ui-plus有关？

你在我其他基础组件项目进群，加我微信聊吧

**Comment by lifangpeng** [comment]
> > 这里是不是和那个t-ui-plus有关？
> 
> 你在我其他基础组件项目进群，加我微信聊吧

你说的在哪里找项目群，我没有找到哟

**Comment by wocwin** [comment]
> > > 这里是不是和那个t-ui-plus有关？
> > 
> > 
> > 你在我其他基础组件项目进群，加我微信聊吧
> 
> 你说的在哪里找项目群，我没有找到哟

到我github首页，最前面两个开源的项目就有

**Comment by wocwin** [comment]
![Uploading D8D4B2B6-850D-4221-83CC-E7E160871B64.png…]()

**Comment by wocwin** [comment]
> rollPane.vue:21 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener') ScrollPane.vue:21:1
> 
> 发现这行代码有 const scrollWrapper = computed(() => proxy.$refs.scrollContainer.$refs.wrap$);
> 
> onMounted(() => { scrollWrapper.value.addEventListener('scroll', emitScroll, true) })

已经重写了代码，集成了主题切换及layout布局拆分，使用pnpm安装
