### ISSUE TITLE
下拉选择表格组件t-select-table,显示查询条件的情况下，选择查询条件带有下拉框会导致显示出来的显示出来的下拉选择组件关闭

### ISSUE THREAD

**Issue by zcq111** [wocwin/wocwin-admin#6]
步骤：
1、下拉选择表格组件t-select-table（带显示查询条件）
![image](https://github.com/wocwin/wocwin-admin/assets/39423986/8f6b57cc-2777-4a93-84bb-94085c1f0b48)
2、选择查询条件里的下拉选项
![image](https://github.com/wocwin/wocwin-admin/assets/39423986/582dcbc2-d94c-47f5-9105-cf4c92b8ca9e)
3、下拉表格不见了
![image](https://github.com/wocwin/wocwin-admin/assets/39423986/34a9208e-371d-4294-9546-5a08d0eeeee0)

问题：
选择查询条件里的下拉选项不应该关闭下拉表格，应该是选择下拉表格里的某个记录选项才关闭。

**Comment by wocwin** [comment]
已经解决，请安装t-ui-plus1.2.5版本

**Comment by wocwin** [comment]
已经解决
